package transacao.Controllers;

import java.util.Random;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.ModelAndView;

import transacao.Models.Role;
import transacao.Models.Usuario;
import transacao.Repositories.RepositoryUser;
import transacao.Service.EmailSenderService;
import transacao.Service.Senha;

@Controller
public class LoginController {
	
	@Autowired
	private RepositoryUser repositoryUser;
	
	@Autowired
	private PasswordEncoder passwordEncoder;
	
	@Autowired
	private EmailSenderService senderService;
	
	
	@RequestMapping("/login")
	public String login() throws Exception {
	
		/*
		Usuario usuario = new Usuario();
		usuario.setEmail("hebertyprado22005@gmail.com");
		usuario.setPassword(passwordEncoder.encode("Elokonamoda"));
		usuario.setRole(Role.USER.getNome());
		usuario.setUsername("Hebert");
		
		this.repositoryUser.save(usuario);
		*/
		
		
		return "Autenticacao/login.html";
	}
	
	
	@RequestMapping("/cadastrar")
	public ModelAndView Cadastro() {
	
		
		return new ModelAndView("Autenticacao/cadastro.html");
	}
	
	
	@PostMapping("/cadastrar")
	public ModelAndView Cadastrar(@RequestParam("nome") String nome, @RequestParam("email") String email) {
		
		int senha = Senha.autoGenerated(6);
		System.out.println("senha: " + senha);
		
		senderService.sendEmail(email, "Senha para acesso do projeto de controle de transações", "olá " + nome + " agradeço por criar conta e poder entrar e interagir no meu projeto, espero a sua opinião sobre esse trabalho ! \nSenha: " + senha);
		
		return new ModelAndView("redirect:/login");
	}


}
